/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012231137.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_EXAMPLES_Interface1_STUB_HPP_
#define V0_COMMONAPI_EXAMPLES_Interface1_STUB_HPP_

#include <functional>
#include <sstream>




#include <v0/commonapi/examples/Interface1.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <vector>

#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {
namespace examples {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service Interface1. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class Interface1StubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual Interface1 {
 public:
    ///Notifies all remote listeners about a change of value of the attribute aString.
    virtual void fireAStringAttributeChanged(const std::string &aString) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockAStringAttribute(bool _lockAccess) {
        if (_lockAccess) {
            aStringMutex_.lock();
        } else {
            aStringMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex aStringMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for Interface1.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class Interface1StubRemoteEvent
{
public:
    virtual ~Interface1StubRemoteEvent() { }

    /// Verification callback for remote set requests on the attribute aString
    virtual bool onRemoteSetAStringAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _value) = 0;
    /// Action callback for remote set requests on the attribute aString
    virtual void onRemoteAStringAttributeChanged() = 0;
};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service Interface1 to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class Interface1Stub
    : public virtual CommonAPI::Stub<Interface1StubAdapter, Interface1StubRemoteEvent>
{
public:
    typedef std::function<void ()> setUInt32Reply_t;
    typedef std::function<void (uint32_t _value)> getUInt32Reply_t;

    virtual ~Interface1Stub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 3);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Provides getter access to the attribute aString
    virtual const std::string &getAStringAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireAStringAttributeChanged(std::string _value) {
    auto stubAdapter = CommonAPI::Stub<Interface1StubAdapter, Interface1StubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireAStringAttributeChanged(_value);
    }
    void lockAStringAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<Interface1StubAdapter, Interface1StubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockAStringAttribute(_lockAccess);
    }
    /// This is the method that will be called on remote calls on the method setUInt32.
    virtual void setUInt32(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _value, setUInt32Reply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method getUInt32.
    virtual void getUInt32(const std::shared_ptr<CommonAPI::ClientId> _client, getUInt32Reply_t _reply) = 0;


    using CommonAPI::Stub<Interface1StubAdapter, Interface1StubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<Interface1StubAdapter, Interface1StubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<Interface1StubAdapter, Interface1StubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef Interface1StubRemoteEvent RemoteEventType;
    typedef Interface1 StubInterface;
};

} // namespace examples
} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_EXAMPLES_Interface1_STUB_HPP_
